// src/context/TransactionsContext.jsx
// ✅ M26: Sub-contexto para gestión de transacciones
// ✅ Fase 5: Supabase sync via user_data table
import React, { createContext, useContext, useState, useEffect, useCallback, useMemo, useRef } from 'react';
import StorageManager from '../modules/storage/StorageManager';
import { INITIAL_TRANSACTIONS } from '../config/initialData';
import { loadFromSupabase, saveToSupabase } from '../modules/supabase/syncUtils';

const SYNC_KEY = 'transactions_v5';

const TransactionsContext = createContext();

export const useTransactions = () => {
  const context = useContext(TransactionsContext);
  if (!context) {
    throw new Error('useTransactions debe usarse dentro de TransactionsProvider');
  }
  return context;
};

export function TransactionsProvider({ children, currentUser }) {
  const [transactions, setTransactions] = useState(() =>
    StorageManager.load(SYNC_KEY, INITIAL_TRANSACTIONS)
  );
  const syncReady = useRef(false);

  // Generate missing auto-instances for recurring transactions
  const generateRecurringInstances = useCallback((allTransactions) => {
    const templates = allTransactions.filter(tx => tx.recurringId && tx.id === tx.recurringId);
    if (templates.length === 0) return [];

    const today = new Date();
    const currentYM = `${today.getFullYear()}-${String(today.getMonth() + 1).padStart(2, '0')}`;
    const toAdd = [];

    for (const template of templates) {
      const templateDate = new Date(template.date + 'T00:00:00');
      const templateDay = templateDate.getDate();
      let year = templateDate.getFullYear();
      let month = templateDate.getMonth() + 1;

      // Start from the month after the template
      month++;
      if (month > 12) { month = 1; year++; }

      while (true) {
        const ym = `${year}-${String(month).padStart(2, '0')}`;
        if (ym > currentYM) break;

        const exists = allTransactions.some(tx =>
          tx.recurringId === template.id &&
          tx.id !== template.id &&
          tx.date?.startsWith(ym)
        ) || toAdd.some(tx =>
          tx.recurringId === template.id &&
          tx.date?.startsWith(ym)
        );

        if (!exists) {
          const daysInMonth = new Date(year, month, 0).getDate();
          const day = Math.min(templateDay, daysInMonth);
          const dateStr = `${ym}-${String(day).padStart(2, '0')}`;
          toAdd.push({
            ...template,
            id: `tx_auto_${template.id}_${ym}`,
            date: dateStr,
            autoGenerated: true,
            createdAt: new Date().toISOString()
          });
        }

        month++;
        if (month > 12) { month = 1; year++; }
      }
    }

    return toAdd;
  }, []);

  // Load from Supabase on mount (once) — overrides localStorage if cloud has data
  useEffect(() => {
    loadFromSupabase(SYNC_KEY).then(data => {
      syncReady.current = true;
      const base = Array.isArray(data) && data.length > 0 ? data : null;
      if (base) {
        const generated = generateRecurringInstances(base);
        const merged = generated.length > 0 ? [...base, ...generated] : base;
        setTransactions(merged);
        StorageManager.save(SYNC_KEY, merged);
      } else {
        // Still generate from localStorage data
        setTransactions(prev => {
          const generated = generateRecurringInstances(prev);
          if (generated.length === 0) return prev;
          return [...prev, ...generated];
        });
      }
    });
  }, [generateRecurringInstances]);

  // Save to localStorage + Supabase on every change (after initial sync)
  useEffect(() => {
    StorageManager.save(SYNC_KEY, transactions);
    if (syncReady.current) saveToSupabase(SYNC_KEY, transactions);
  }, [transactions]);

  // ✅ Agregar transacción
  const addTransaction = useCallback((transaction) => {
    const id = `tx_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`;
    const newTransaction = {
      id,
      date: transaction.date || new Date().toISOString().split('T')[0],
      description: transaction.description || 'Sin descripción',
      amount: parseFloat(transaction.amount) || 0,
      currency: transaction.currency || 'EUR',
      categoryId: transaction.categoryId || null,
      paymentMethod: transaction.paymentMethod || 'Tarjeta',
      notes: transaction.notes || '',
      imported: transaction.imported || false,
      importedAt: transaction.importedAt || null,
      recurrence: transaction.recurrence || null,
      recurringId: transaction.recurrence ? id : null,
      autoGenerated: false,
      createdAt: new Date().toISOString(),
      user: transaction.user || currentUser
    };

    setTransactions(prev => [...prev, newTransaction]);
    return true;
  }, [currentUser]);

  // ✅ Agregar transacciones en batch
  const addTransactionsBatch = useCallback((transactionsArray) => {
    if (!Array.isArray(transactionsArray) || transactionsArray.length === 0) {
      return { success: false, count: 0 };
    }

    const timestamp = Date.now();
    
    const newTransactions = transactionsArray.map((tx, index) => ({
      id: `tx_${timestamp}_${index}_${Math.random().toString(36).substr(2, 9)}`,
      date: tx.date || new Date().toISOString().split('T')[0],
      description: tx.description || 'Sin descripción',
      amount: parseFloat(tx.amount) || 0,
      currency: tx.currency || 'EUR',
      categoryId: tx.categoryId || null,
      paymentMethod: tx.paymentMethod || 'Tarjeta',
      notes: tx.notes || '',
      imported: tx.imported || false,
      importedAt: tx.importedAt || null,
      createdAt: new Date().toISOString(),
      user: tx.user || currentUser
    }));

    setTransactions(prev => [...prev, ...newTransactions]);
    return { success: true, count: newTransactions.length };
  }, [currentUser]);

  // ✅ Actualizar transacción
  const updateTransaction = useCallback((transactionId, updates) => {
    setTransactions(prev => prev.map(tx => 
      tx.id === transactionId 
        ? { ...tx, ...updates, updatedAt: new Date().toISOString() }
        : tx
    ));
    return true;
  }, []);

  // ✅ Eliminar transacción
  const deleteTransaction = useCallback((transactionId) => {
    setTransactions(prev => prev.filter(tx => tx.id !== transactionId));
    return true;
  }, []);

  // ✅ Limpiar todas
  const clearAllTransactions = useCallback(() => {
    setTransactions([]);
    return true;
  }, []);

  // ✅ M25: Índice pre-calculado por mes y categoría
  const transactionIndex = useMemo(() => {
    const index = {
      byMonth: {},
      byCategory: {},
      byMonthAndCategory: {}
    };

    transactions.forEach(tx => {
      const month = tx.date?.slice(0, 7);
      const catId = tx.categoryId;

      // Por mes
      if (month) {
        if (!index.byMonth[month]) index.byMonth[month] = [];
        index.byMonth[month].push(tx);
      }

      // Por categoría
      if (catId) {
        if (!index.byCategory[catId]) index.byCategory[catId] = [];
        index.byCategory[catId].push(tx);
      }

      // Por mes Y categoría
      if (month && catId) {
        const key = `${month}:${catId}`;
        if (!index.byMonthAndCategory[key]) index.byMonthAndCategory[key] = [];
        index.byMonthAndCategory[key].push(tx);
      }
    });

    return index;
  }, [transactions]);

  // ✅ M25: Obtener transacciones por mes (O(1) en vez de O(n))
  const getTransactionsByMonth = useCallback((month) => {
    return transactionIndex.byMonth[month] || [];
  }, [transactionIndex]);

  // ✅ M25: Obtener transacciones por categoría y mes (O(1))
  const getTransactionsByCategoryAndMonth = useCallback((categoryId, month) => {
    const key = `${month}:${categoryId}`;
    return transactionIndex.byMonthAndCategory[key] || [];
  }, [transactionIndex]);

  const value = useMemo(() => ({
    transactions,
    setTransactions,
    addTransaction,
    addTransactionsBatch,
    updateTransaction,
    deleteTransaction,
    clearAllTransactions,
    // M25: Funciones optimizadas
    transactionIndex,
    getTransactionsByMonth,
    getTransactionsByCategoryAndMonth
  }), [
    transactions,
    addTransaction,
    addTransactionsBatch,
    updateTransaction,
    deleteTransaction,
    clearAllTransactions,
    transactionIndex,
    getTransactionsByMonth,
    getTransactionsByCategoryAndMonth
  ]);

  return (
    <TransactionsContext.Provider value={value}>
      {children}
    </TransactionsContext.Provider>
  );
}